### PR TITLE
Added cypress and basic testing code

### PR DESCRIPTION
**Pull request by Suvrat1629**
I have configured cypress and added basic testing code for the html files based on how they are coded, the only failing test case at the moment is the "toggleLightDark() not found" as this function is not defined yet. 
I have also added a e2e-tests.yml filewhich works on CI.

### CODE REVIEW

**Comment by lcrojano** [comment]
@Suvrat1629, could you update your work with the latest changes to fix conflicts?

**Comment by Suvrat1629** [comment]
I think the conflicts are occurring in the package.json file if I am not wrong which is because i have added scripts to open and run cypress, which shouldn't be a problem. Is this the issue or is there any other conflict occurring?

**Comment by Suvrat1629** [comment]
@lcrojano updates?

**Comment by lcrojano** [comment]
@Suvrat1629  Thanks for your response! The conflict is actually in the package-lock.json file, not package.json. This typically happens when different branches modify the dependency tree, causing discrepancies in the lock file.

The package-lock.json ensures consistent dependencies across environments, so it's important to resolve this properly.

To resolve the conflict:

Pull the latest changes from the target branch (main, for example).

``` bash
git pull origin main
```
Resolve the conflict in the package-lock.json. A simple approach is to delete the package-lock.json file, run npm install to regenerate it, and then commit the new lock file.


``` bash
rm package-lock.json
npm install
```
After resolving, commit the new package-lock.json and push it to the PR branch:

``` bash
git add package-lock.json
git commit -m "chore: solve package-lock.json conflict"
git push origin <your-branch>
```
Let me know what do you think.

**Comment by Suvrat1629** [comment]
I have made the changes and followed the steps as you have told me to but i think re-adding the package-lock.json has changed the placement of code please review it and tell me if there is any issue.

**Pull request merged**
